const trainingData = [
  // Food & Dining
  { description: 'Starbucks coffee', category: 'Food & Dining' },
  { description: 'McDonald\'s lunch', category: 'Food & Dining' },
  { description: 'Pizza delivery', category: 'Food & Dining' },
  { description: 'Restaurant dinner', category: 'Food & Dining' },
  { description: 'Grocery shopping', category: 'Food & Dining' },
  { description: 'Food delivery', category: 'Food & Dining' },
  { description: 'Coffee shop', category: 'Food & Dining' },
  { description: 'Fast food', category: 'Food & Dining' },
  { description: 'Takeout food', category: 'Food & Dining' },
  { description: 'Dining out', category: 'Food & Dining' },
  { description: 'Cafe visit', category: 'Food & Dining' },
  { description: 'Lunch at work', category: 'Food & Dining' },
  { description: 'Dinner with friends', category: 'Food & Dining' },
  { description: 'Breakfast', category: 'Food & Dining' },
  { description: 'Snacks', category: 'Food & Dining' },
  { description: 'Food court', category: 'Food & Dining' },
  { description: 'Bakery', category: 'Food & Dining' },
  { description: 'Ice cream', category: 'Food & Dining' },
  { description: 'Food truck', category: 'Food & Dining' },
  { description: 'Catering', category: 'Food & Dining' },

  // Transportation
  { description: 'Uber ride', category: 'Transportation' },
  { description: 'Lyft trip', category: 'Transportation' },
  { description: 'Taxi fare', category: 'Transportation' },
  { description: 'Gas station', category: 'Transportation' },
  { description: 'Parking fee', category: 'Transportation' },
  { description: 'Bus fare', category: 'Transportation' },
  { description: 'Train ticket', category: 'Transportation' },
  { description: 'Subway fare', category: 'Transportation' },
  { description: 'Car maintenance', category: 'Transportation' },
  { description: 'Oil change', category: 'Transportation' },
  { description: 'Car wash', category: 'Transportation' },
  { description: 'Toll road', category: 'Transportation' },
  { description: 'Airport parking', category: 'Transportation' },
  { description: 'Rental car', category: 'Transportation' },
  { description: 'Bike rental', category: 'Transportation' },
  { description: 'Scooter rental', category: 'Transportation' },
  { description: 'Car insurance', category: 'Transportation' },
  { description: 'Auto repair', category: 'Transportation' },
  { description: 'Tire replacement', category: 'Transportation' },
  { description: 'Car registration', category: 'Transportation' },

  // Shopping
  { description: 'Amazon purchase', category: 'Shopping' },
  { description: 'Walmart shopping', category: 'Shopping' },
  { description: 'Target purchase', category: 'Shopping' },
  { description: 'Online shopping', category: 'Shopping' },
  { description: 'Clothing store', category: 'Shopping' },
  { description: 'Electronics store', category: 'Shopping' },
  { description: 'Book store', category: 'Shopping' },
  { description: 'Shoe store', category: 'Shopping' },
  { description: 'Department store', category: 'Shopping' },
  { description: 'Mall shopping', category: 'Shopping' },
  { description: 'Furniture store', category: 'Shopping' },
  { description: 'Home goods', category: 'Shopping' },
  { description: 'Sporting goods', category: 'Shopping' },
  { description: 'Jewelry store', category: 'Shopping' },
  { description: 'Cosmetics store', category: 'Shopping' },
  { description: 'Toy store', category: 'Shopping' },
  { description: 'Pet store', category: 'Shopping' },
  { description: 'Hardware store', category: 'Shopping' },
  { description: 'Garden center', category: 'Shopping' },
  { description: 'Thrift store', category: 'Shopping' },
  { description: 'Outlet mall', category: 'Shopping' },
  { description: 'Online retailer', category: 'Shopping' },

  // Entertainment
  { description: 'Netflix subscription', category: 'Entertainment' },
  { description: 'Movie theater', category: 'Entertainment' },
  { description: 'Concert tickets', category: 'Entertainment' },
  { description: 'Sports event', category: 'Entertainment' },
  { description: 'Theme park', category: 'Entertainment' },
  { description: 'Bowling alley', category: 'Entertainment' },
  { description: 'Arcade games', category: 'Entertainment' },
  { description: 'Gym membership', category: 'Entertainment' },
  { description: 'Yoga class', category: 'Entertainment' },
  { description: 'Fitness center', category: 'Entertainment' },
  { description: 'Swimming pool', category: 'Entertainment' },
  { description: 'Golf course', category: 'Entertainment' },
  { description: 'Tennis court', category: 'Entertainment' },
  { description: 'Video games', category: 'Entertainment' },
  { description: 'Board games', category: 'Entertainment' },
  { description: 'Hobby supplies', category: 'Entertainment' },
  { description: 'Art supplies', category: 'Entertainment' },
  { description: 'Music lessons', category: 'Entertainment' },
  { description: 'Dance class', category: 'Entertainment' },
  { description: 'Theater tickets', category: 'Entertainment' },
  { description: 'Comedy club', category: 'Entertainment' },
  { description: 'Karaoke', category: 'Entertainment' },
  { description: 'Escape room', category: 'Entertainment' },

  // Healthcare
  { description: 'Doctor visit', category: 'Healthcare' },
  { description: 'Dentist appointment', category: 'Healthcare' },
  { description: 'Pharmacy', category: 'Healthcare' },
  { description: 'Prescription medication', category: 'Healthcare' },
  { description: 'Hospital visit', category: 'Healthcare' },
  { description: 'Medical test', category: 'Healthcare' },
  { description: 'Eye exam', category: 'Healthcare' },
  { description: 'Glasses', category: 'Healthcare' },
  { description: 'Contact lenses', category: 'Healthcare' },
  { description: 'Physical therapy', category: 'Healthcare' },
  { description: 'Chiropractor', category: 'Healthcare' },
  { description: 'Massage therapy', category: 'Healthcare' },
  { description: 'Mental health', category: 'Healthcare' },
  { description: 'Counseling', category: 'Healthcare' },
  { description: 'Medical insurance', category: 'Healthcare' },
  { description: 'Dental insurance', category: 'Healthcare' },
  { description: 'Vision insurance', category: 'Healthcare' },
  { description: 'Medical equipment', category: 'Healthcare' },
  { description: 'First aid supplies', category: 'Healthcare' },
  { description: 'Vitamins', category: 'Healthcare' },
  { description: 'Supplements', category: 'Healthcare' },
  { description: 'Health food', category: 'Healthcare' },

  // Utilities
  { description: 'Electric bill', category: 'Utilities' },
  { description: 'Water bill', category: 'Utilities' },
  { description: 'Gas bill', category: 'Utilities' },
  { description: 'Internet service', category: 'Utilities' },
  { description: 'Phone bill', category: 'Utilities' },
  { description: 'Cable TV', category: 'Utilities' },
  { description: 'Streaming service', category: 'Utilities' },
  { description: 'Garbage collection', category: 'Utilities' },
  { description: 'Sewer bill', category: 'Utilities' },
  { description: 'Heating bill', category: 'Utilities' },
  { description: 'Cooling bill', category: 'Utilities' },
  { description: 'Lawn service', category: 'Utilities' },
  { description: 'Snow removal', category: 'Utilities' },
  { description: 'Security system', category: 'Utilities' },
  { description: 'Home maintenance', category: 'Utilities' },
  { description: 'Plumbing service', category: 'Utilities' },
  { description: 'Electrical service', category: 'Utilities' },
  { description: 'HVAC service', category: 'Utilities' },
  { description: 'Pest control', category: 'Utilities' },
  { description: 'Cleaning service', category: 'Utilities' },

  // Housing
  { description: 'Rent payment', category: 'Housing' },
  { description: 'Mortgage payment', category: 'Housing' },
  { description: 'Property tax', category: 'Housing' },
  { description: 'Home insurance', category: 'Housing' },
  { description: 'Renter insurance', category: 'Housing' },
  { description: 'Home improvement', category: 'Housing' },
  { description: 'Furniture', category: 'Housing' },
  { description: 'Appliances', category: 'Housing' },
  { description: 'Kitchen remodel', category: 'Housing' },
  { description: 'Bathroom remodel', category: 'Housing' },
  { description: 'Paint supplies', category: 'Housing' },
  { description: 'Flooring', category: 'Housing' },
  { description: 'Roof repair', category: 'Housing' },
  { description: 'Window replacement', category: 'Housing' },
  { description: 'Door installation', category: 'Housing' },
  { description: 'Deck construction', category: 'Housing' },
  { description: 'Fence installation', category: 'Housing' },
  { description: 'Landscaping', category: 'Housing' },
  { description: 'Garden supplies', category: 'Housing' },
  { description: 'Storage unit', category: 'Housing' },
  { description: 'Moving expenses', category: 'Housing' },

  // Education
  { description: 'Tuition payment', category: 'Education' },
  { description: 'Student loan', category: 'Education' },
  { description: 'Textbooks', category: 'Education' },
  { description: 'School supplies', category: 'Education' },
  { description: 'Online course', category: 'Education' },
  { description: 'Workshop', category: 'Education' },
  { description: 'Seminar', category: 'Education' },
  { description: 'Conference', category: 'Education' },
  { description: 'Training program', category: 'Education' },
  { description: 'Certification exam', category: 'Education' },
  { description: 'Library fee', category: 'Education' },
  { description: 'Lab fee', category: 'Education' },
  { description: 'Activity fee', category: 'Education' },
  { description: 'Graduation fee', category: 'Education' },
  { description: 'Study materials', category: 'Education' },
  { description: 'Software license', category: 'Education' },
  { description: 'Research materials', category: 'Education' },
  { description: 'Academic journal', category: 'Education' },
  { description: 'Professional development', category: 'Education' },
  { description: 'Language class', category: 'Education' },
  { description: 'Cooking class', category: 'Education' },
  { description: 'Photography class', category: 'Education' },

  // Travel
  { description: 'Airplane ticket', category: 'Travel' },
  { description: 'Hotel booking', category: 'Travel' },
  { description: 'Vacation rental', category: 'Travel' },
  { description: 'Car rental', category: 'Travel' },
  { description: 'Travel insurance', category: 'Travel' },
  { description: 'Tour guide', category: 'Travel' },
  { description: 'Sightseeing tour', category: 'Travel' },
  { description: 'Cruise booking', category: 'Travel' },
  { description: 'Train ticket', category: 'Travel' },
  { description: 'Bus ticket', category: 'Travel' },
  { description: 'Ferry ticket', category: 'Travel' },
  { description: 'Souvenirs', category: 'Travel' },
  { description: 'Travel accessories', category: 'Travel' },
  { description: 'Luggage', category: 'Travel' },
  { description: 'Passport fee', category: 'Travel' },
  { description: 'Visa fee', category: 'Travel' },
  { description: 'Airport transfer', category: 'Travel' },
  { description: 'Travel agency', category: 'Travel' },
  { description: 'Vacation package', category: 'Travel' },
  { description: 'Adventure tour', category: 'Travel' },
  { description: 'Ski resort', category: 'Travel' },
  { description: 'Beach resort', category: 'Travel' },
  { description: 'Camping gear', category: 'Travel' },

  // Personal Care
  { description: 'Hair salon', category: 'Personal Care' },
  { description: 'Barber shop', category: 'Personal Care' },
  { description: 'Nail salon', category: 'Personal Care' },
  { description: 'Spa treatment', category: 'Personal Care' },
  { description: 'Facial treatment', category: 'Personal Care' },
  { description: 'Massage', category: 'Personal Care' },
  { description: 'Personal trainer', category: 'Personal Care' },
  { description: 'Nutritionist', category: 'Personal Care' },
  { description: 'Cosmetics', category: 'Personal Care' },
  { description: 'Skincare products', category: 'Personal Care' },
  { description: 'Hair products', category: 'Personal Care' },
  { description: 'Perfume', category: 'Personal Care' },
  { description: 'Makeup', category: 'Personal Care' },
  { description: 'Toiletries', category: 'Personal Care' },
  { description: 'Shampoo', category: 'Personal Care' },
  { description: 'Soap', category: 'Personal Care' },
  { description: 'Toothpaste', category: 'Personal Care' },
  { description: 'Deodorant', category: 'Personal Care' },
  { description: 'Razor blades', category: 'Personal Care' },
  { description: 'Hair dryer', category: 'Personal Care' },
  { description: 'Mirror', category: 'Personal Care' },
  { description: 'Towel', category: 'Personal Care' },
  { description: 'Bathrobe', category: 'Personal Care' },

  // Insurance
  { description: 'Life insurance', category: 'Insurance' },
  { description: 'Health insurance', category: 'Insurance' },
  { description: 'Auto insurance', category: 'Insurance' },
  { description: 'Home insurance', category: 'Insurance' },
  { description: 'Renter insurance', category: 'Insurance' },
  { description: 'Disability insurance', category: 'Insurance' },
  { description: 'Pet insurance', category: 'Insurance' },
  { description: 'Travel insurance', category: 'Insurance' },
  { description: 'Umbrella insurance', category: 'Insurance' },
  { description: 'Flood insurance', category: 'Insurance' },
  { description: 'Earthquake insurance', category: 'Insurance' },
  { description: 'Business insurance', category: 'Insurance' },
  { description: 'Professional liability', category: 'Insurance' },
  { description: 'Malpractice insurance', category: 'Insurance' },
  { description: 'Workers compensation', category: 'Insurance' },
  { description: 'Unemployment insurance', category: 'Insurance' },
  { description: 'Social security', category: 'Insurance' },
  { description: 'Medicare', category: 'Insurance' },
  { description: 'Medicaid', category: 'Insurance' },
  { description: 'Dental insurance', category: 'Insurance' },
  { description: 'Vision insurance', category: 'Insurance' },
  { description: 'Long term care', category: 'Insurance' },
  { description: 'Annuity', category: 'Insurance' },

  // Investments
  { description: 'Stock purchase', category: 'Investments' },
  { description: 'Bond purchase', category: 'Investments' },
  { description: 'Mutual fund', category: 'Investments' },
  { description: 'ETF purchase', category: 'Investments' },
  { description: '401k contribution', category: 'Investments' },
  { description: 'IRA contribution', category: 'Investments' },
  { description: 'Roth IRA', category: 'Investments' },
  { description: '529 plan', category: 'Investments' },
  { description: 'Real estate investment', category: 'Investments' },
  { description: 'Cryptocurrency', category: 'Investments' },
  { description: 'Gold purchase', category: 'Investments' },
  { description: 'Silver purchase', category: 'Investments' },
  { description: 'Commodities', category: 'Investments' },
  { description: 'Options trading', category: 'Investments' },
  { description: 'Futures trading', category: 'Investments' },
  { description: 'Forex trading', category: 'Investments' },
  { description: 'Investment advisor', category: 'Investments' },
  { description: 'Financial planner', category: 'Investments' },
  { description: 'Brokerage account', category: 'Investments' },
  { description: 'Dividend payment', category: 'Investments' },
  { description: 'Interest income', category: 'Investments' },
  { description: 'Capital gains', category: 'Investments' },
  { description: 'Investment fees', category: 'Investments' },
  { description: 'Trading commission', category: 'Investments' },

  // Other
  { description: 'ATM withdrawal', category: 'Other' },
  { description: 'Bank fee', category: 'Other' },
  { description: 'Credit card fee', category: 'Other' },
  { description: 'Late fee', category: 'Other' },
  { description: 'Service charge', category: 'Other' },
  { description: 'Donation', category: 'Other' },
  { description: 'Charity', category: 'Other' },
  { description: 'Gift', category: 'Other' },
  { description: 'Cash back', category: 'Other' },
  { description: 'Refund', category: 'Other' },
  { description: 'Rebate', category: 'Other' },
  { description: 'Reward points', category: 'Other' },
  { description: 'Membership fee', category: 'Other' },
  { description: 'Subscription', category: 'Other' },
  { description: 'Software license', category: 'Other' },
  { description: 'App purchase', category: 'Other' },
  { description: 'Digital download', category: 'Other' },
  { description: 'Online service', category: 'Other' },
  { description: 'Web hosting', category: 'Other' },
  { description: 'Domain registration', category: 'Other' },
  { description: 'Cloud storage', category: 'Other' },
  { description: 'Backup service', category: 'Other' },
  { description: 'Security software', category: 'Other' },
  { description: 'Antivirus', category: 'Other' },
  { description: 'VPN service', category: 'Other' },
  { description: 'Password manager', category: 'Other' }
];

module.exports = trainingData;
